# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ventanaPrincipal(object):
    def setupUi(self, ventanaPrincipal):
        ventanaPrincipal.setObjectName("ventanaPrincipal")
        ventanaPrincipal.resize(1183, 702)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ventanaPrincipal.sizePolicy().hasHeightForWidth())
        ventanaPrincipal.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(ventanaPrincipal)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.videoFolder_label = QtWidgets.QLabel(ventanaPrincipal)
        self.videoFolder_label.setObjectName("videoFolder_label")
        self.verticalLayout.addWidget(self.videoFolder_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filePath_edit = QtWidgets.QLineEdit(ventanaPrincipal)
        self.filePath_edit.setObjectName("filePath_edit")
        self.horizontalLayout_2.addWidget(self.filePath_edit)
        self.selectFile_button = QtWidgets.QPushButton(ventanaPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectFile_button.sizePolicy().hasHeightForWidth())
        self.selectFile_button.setSizePolicy(sizePolicy)
        self.selectFile_button.setObjectName("selectFile_button")
        self.horizontalLayout_2.addWidget(self.selectFile_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imagesFolder_label = QtWidgets.QLabel(ventanaPrincipal)
        self.imagesFolder_label.setObjectName("imagesFolder_label")
        self.verticalLayout_2.addWidget(self.imagesFolder_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.folderPath_edit = QtWidgets.QLineEdit(ventanaPrincipal)
        self.folderPath_edit.setText("")
        self.folderPath_edit.setObjectName("folderPath_edit")
        self.horizontalLayout_3.addWidget(self.folderPath_edit)
        self.selectFolder_button = QtWidgets.QPushButton(ventanaPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectFolder_button.sizePolicy().hasHeightForWidth())
        self.selectFolder_button.setSizePolicy(sizePolicy)
        self.selectFolder_button.setObjectName("selectFolder_button")
        self.horizontalLayout_3.addWidget(self.selectFolder_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(ventanaPrincipal)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.trajectories_button = QtWidgets.QPushButton(ventanaPrincipal)
        self.trajectories_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trajectories_button.sizePolicy().hasHeightForWidth())
        self.trajectories_button.setSizePolicy(sizePolicy)
        self.trajectories_button.setMinimumSize(QtCore.QSize(90, 0))
        self.trajectories_button.setObjectName("trajectories_button")
        self.horizontalLayout_12.addWidget(self.trajectories_button)
        self.removeDrift_checkBox = QtWidgets.QCheckBox(ventanaPrincipal)
        self.removeDrift_checkBox.setObjectName("removeDrift_checkBox")
        self.horizontalLayout_12.addWidget(self.removeDrift_checkBox)
        self.gridLayout.addLayout(self.horizontalLayout_12, 2, 3, 2, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.saveAsImages_button = QtWidgets.QPushButton(ventanaPrincipal)
        self.saveAsImages_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAsImages_button.sizePolicy().hasHeightForWidth())
        self.saveAsImages_button.setSizePolicy(sizePolicy)
        self.saveAsImages_button.setMinimumSize(QtCore.QSize(100, 0))
        self.saveAsImages_button.setObjectName("saveAsImages_button")
        self.horizontalLayout_4.addWidget(self.saveAsImages_button)
        self.saveAsImages_progressBar = QtWidgets.QProgressBar(ventanaPrincipal)
        self.saveAsImages_progressBar.setProperty("value", 0)
        self.saveAsImages_progressBar.setObjectName("saveAsImages_progressBar")
        self.horizontalLayout_4.addWidget(self.saveAsImages_progressBar)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.play_button = QtWidgets.QPushButton(ventanaPrincipal)
        self.play_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_button.sizePolicy().hasHeightForWidth())
        self.play_button.setSizePolicy(sizePolicy)
        self.play_button.setMinimumSize(QtCore.QSize(100, 0))
        self.play_button.setCheckable(False)
        self.play_button.setObjectName("play_button")
        self.horizontalLayout_9.addWidget(self.play_button)
        self.fpsLayout = QtWidgets.QVBoxLayout()
        self.fpsLayout.setObjectName("fpsLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectFps_label = QtWidgets.QLabel(ventanaPrincipal)
        self.selectFps_label.setObjectName("selectFps_label")
        self.horizontalLayout.addWidget(self.selectFps_label)
        self.playFps_label = QtWidgets.QLabel(ventanaPrincipal)
        self.playFps_label.setObjectName("playFps_label")
        self.horizontalLayout.addWidget(self.playFps_label)
        spacerItem = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.playLength_label = QtWidgets.QLabel(ventanaPrincipal)
        self.playLength_label.setObjectName("playLength_label")
        self.horizontalLayout.addWidget(self.playLength_label)
        self.fpsLayout.addLayout(self.horizontalLayout)
        self.playFps_slider = QtWidgets.QSlider(ventanaPrincipal)
        self.playFps_slider.setMinimum(1)
        self.playFps_slider.setMaximum(120)
        self.playFps_slider.setProperty("value", 30)
        self.playFps_slider.setOrientation(QtCore.Qt.Horizontal)
        self.playFps_slider.setObjectName("playFps_slider")
        self.fpsLayout.addWidget(self.playFps_slider)
        self.horizontalLayout_9.addLayout(self.fpsLayout)
        self.gridLayout.addLayout(self.horizontalLayout_9, 4, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(ventanaPrincipal)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(ventanaPrincipal)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 6, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(ventanaPrincipal)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(ventanaPrincipal)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.minHeight_slider = QtWidgets.QSlider(ventanaPrincipal)
        self.minHeight_slider.setMaximum(800)
        self.minHeight_slider.setOrientation(QtCore.Qt.Vertical)
        self.minHeight_slider.setObjectName("minHeight_slider")
        self.horizontalLayout_6.addWidget(self.minHeight_slider)
        self.maxHeight_slider = QtWidgets.QSlider(ventanaPrincipal)
        self.maxHeight_slider.setMaximum(800)
        self.maxHeight_slider.setProperty("value", 800)
        self.maxHeight_slider.setOrientation(QtCore.Qt.Vertical)
        self.maxHeight_slider.setObjectName("maxHeight_slider")
        self.horizontalLayout_6.addWidget(self.maxHeight_slider)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout_7, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 2, 1, 1)
        self.tracking_tableView = QtWidgets.QTableView(ventanaPrincipal)
        self.tracking_tableView.setObjectName("tracking_tableView")
        self.gridLayout.addWidget(self.tracking_tableView, 6, 3, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(ventanaPrincipal)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(ventanaPrincipal)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.minWidth_slider = QtWidgets.QSlider(ventanaPrincipal)
        self.minWidth_slider.setMaximum(1280)
        self.minWidth_slider.setOrientation(QtCore.Qt.Horizontal)
        self.minWidth_slider.setObjectName("minWidth_slider")
        self.verticalLayout_6.addWidget(self.minWidth_slider)
        self.maxWidth_slider = QtWidgets.QSlider(ventanaPrincipal)
        self.maxWidth_slider.setMaximum(1280)
        self.maxWidth_slider.setProperty("value", 1280)
        self.maxWidth_slider.setOrientation(QtCore.Qt.Horizontal)
        self.maxWidth_slider.setObjectName("maxWidth_slider")
        self.verticalLayout_6.addWidget(self.maxWidth_slider)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        self.close_button = QtWidgets.QPushButton(ventanaPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        self.close_button.setObjectName("close_button")
        self.gridLayout.addWidget(self.close_button, 7, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(ventanaPrincipal)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 8, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.refreshData_button = QtWidgets.QPushButton(ventanaPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshData_button.sizePolicy().hasHeightForWidth())
        self.refreshData_button.setSizePolicy(sizePolicy)
        self.refreshData_button.setObjectName("refreshData_button")
        self.verticalLayout_3.addWidget(self.refreshData_button)
        self.recDate_label = QtWidgets.QLabel(ventanaPrincipal)
        self.recDate_label.setObjectName("recDate_label")
        self.verticalLayout_3.addWidget(self.recDate_label)
        self.frameCount_label = QtWidgets.QLabel(ventanaPrincipal)
        self.frameCount_label.setObjectName("frameCount_label")
        self.verticalLayout_3.addWidget(self.frameCount_label)
        self.recSpeed_label = QtWidgets.QLabel(ventanaPrincipal)
        self.recSpeed_label.setObjectName("recSpeed_label")
        self.verticalLayout_3.addWidget(self.recSpeed_label)
        self.realTime_label = QtWidgets.QLabel(ventanaPrincipal)
        self.realTime_label.setObjectName("realTime_label")
        self.verticalLayout_3.addWidget(self.realTime_label)
        self.width_label = QtWidgets.QLabel(ventanaPrincipal)
        self.width_label.setObjectName("width_label")
        self.verticalLayout_3.addWidget(self.width_label)
        self.height_label = QtWidgets.QLabel(ventanaPrincipal)
        self.height_label.setObjectName("height_label")
        self.verticalLayout_3.addWidget(self.height_label)
        self.gridLayout.addLayout(self.verticalLayout_3, 9, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.track_button = QtWidgets.QPushButton(ventanaPrincipal)
        self.track_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.track_button.sizePolicy().hasHeightForWidth())
        self.track_button.setSizePolicy(sizePolicy)
        self.track_button.setMinimumSize(QtCore.QSize(90, 0))
        self.track_button.setObjectName("track_button")
        self.horizontalLayout_13.addWidget(self.track_button)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(ventanaPrincipal)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.initialFrame_spinBox = QtWidgets.QSpinBox(ventanaPrincipal)
        self.initialFrame_spinBox.setObjectName("initialFrame_spinBox")
        self.horizontalLayout_10.addWidget(self.initialFrame_spinBox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(ventanaPrincipal)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.finalFrame_spinBox = QtWidgets.QSpinBox(ventanaPrincipal)
        self.finalFrame_spinBox.setObjectName("finalFrame_spinBox")
        self.horizontalLayout_8.addWidget(self.finalFrame_spinBox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.framesFinalminusInitial_label = QtWidgets.QLabel(ventanaPrincipal)
        self.framesFinalminusInitial_label.setObjectName("framesFinalminusInitial_label")
        self.horizontalLayout_13.addWidget(self.framesFinalminusInitial_label)
        self.gridLayout.addLayout(self.horizontalLayout_13, 1, 3, 1, 1)

        self.retranslateUi(ventanaPrincipal)
        self.filePath_edit.textChanged['QString'].connect(self.refreshData_button.click)
        self.playFps_slider.valueChanged['int'].connect(self.playFps_label.setNum)
        self.minHeight_slider.valueChanged['int'].connect(self.label.setNum)
        self.maxHeight_slider.valueChanged['int'].connect(self.label_2.setNum)
        self.minWidth_slider.valueChanged['int'].connect(self.label_4.setNum)
        self.maxWidth_slider.valueChanged['int'].connect(self.label_3.setNum)
        QtCore.QMetaObject.connectSlotsByName(ventanaPrincipal)
        ventanaPrincipal.setTabOrder(self.selectFile_button, self.selectFolder_button)
        ventanaPrincipal.setTabOrder(self.selectFolder_button, self.play_button)
        ventanaPrincipal.setTabOrder(self.play_button, self.saveAsImages_button)
        ventanaPrincipal.setTabOrder(self.saveAsImages_button, self.filePath_edit)
        ventanaPrincipal.setTabOrder(self.filePath_edit, self.folderPath_edit)
        ventanaPrincipal.setTabOrder(self.folderPath_edit, self.playFps_slider)
        ventanaPrincipal.setTabOrder(self.playFps_slider, self.minHeight_slider)
        ventanaPrincipal.setTabOrder(self.minHeight_slider, self.maxHeight_slider)
        ventanaPrincipal.setTabOrder(self.maxHeight_slider, self.minWidth_slider)
        ventanaPrincipal.setTabOrder(self.minWidth_slider, self.maxWidth_slider)
        ventanaPrincipal.setTabOrder(self.maxWidth_slider, self.graphicsView)

    def retranslateUi(self, ventanaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        ventanaPrincipal.setWindowTitle(_translate("ventanaPrincipal", "Video Tools Alpha"))
        self.videoFolder_label.setText(_translate("ventanaPrincipal", "Ruta al archivo de video:"))
        self.selectFile_button.setText(_translate("ventanaPrincipal", "Seleccionar"))
        self.imagesFolder_label.setText(_translate("ventanaPrincipal", "Ruta a la carpeta de imagenes:"))
        self.selectFolder_button.setText(_translate("ventanaPrincipal", "Explorar"))
        self.trajectories_button.setText(_translate("ventanaPrincipal", "Find Trajectories"))
        self.removeDrift_checkBox.setText(_translate("ventanaPrincipal", "Remove Drift"))
        self.saveAsImages_button.setText(_translate("ventanaPrincipal", "Save Video as Images"))
        self.play_button.setText(_translate("ventanaPrincipal", "Play Video"))
        self.selectFps_label.setText(_translate("ventanaPrincipal", "Select Play framerate:"))
        self.playFps_label.setText(_translate("ventanaPrincipal", "30"))
        self.playLength_label.setText(_translate("ventanaPrincipal", "Video Length: "))
        self.label.setText(_translate("ventanaPrincipal", "0"))
        self.label_2.setText(_translate("ventanaPrincipal", "800"))
        self.label_4.setText(_translate("ventanaPrincipal", "0"))
        self.label_3.setText(_translate("ventanaPrincipal", "1280"))
        self.close_button.setText(_translate("ventanaPrincipal", "Close"))
        self.refreshData_button.setText(_translate("ventanaPrincipal", "Refresh Video Info"))
        self.recDate_label.setText(_translate("ventanaPrincipal", "Recording Date:"))
        self.frameCount_label.setText(_translate("ventanaPrincipal", "Frame Count: "))
        self.recSpeed_label.setText(_translate("ventanaPrincipal", "Recording Speed: "))
        self.realTime_label.setText(_translate("ventanaPrincipal", "Recorded Time:"))
        self.width_label.setText(_translate("ventanaPrincipal", "Width:"))
        self.height_label.setText(_translate("ventanaPrincipal", "Height:"))
        self.track_button.setText(_translate("ventanaPrincipal", "Detect Particles"))
        self.label_6.setText(_translate("ventanaPrincipal", "Initial frame:"))
        self.label_7.setText(_translate("ventanaPrincipal", "Final frame:"))
        self.framesFinalminusInitial_label.setText(_translate("ventanaPrincipal", "0 frames"))

