# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ventanaPrincipal(object):
    def setupUi(self, ventanaPrincipal):
        ventanaPrincipal.setObjectName("ventanaPrincipal")
        ventanaPrincipal.resize(574, 464)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ventanaPrincipal.sizePolicy().hasHeightForWidth())
        ventanaPrincipal.setSizePolicy(sizePolicy)
        self.saveAsImages_button = QtWidgets.QPushButton(ventanaPrincipal)
        self.saveAsImages_button.setGeometry(QtCore.QRect(20, 90, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAsImages_button.sizePolicy().hasHeightForWidth())
        self.saveAsImages_button.setSizePolicy(sizePolicy)
        self.saveAsImages_button.setObjectName("saveAsImages_button")
        self.close_button = QtWidgets.QPushButton(ventanaPrincipal)
        self.close_button.setGeometry(QtCore.QRect(20, 230, 131, 51))
        self.close_button.setObjectName("close_button")
        self.status_label = QtWidgets.QLabel(ventanaPrincipal)
        self.status_label.setGeometry(QtCore.QRect(480, 20, 61, 20))
        self.status_label.setObjectName("status_label")
        self.stream_button = QtWidgets.QRadioButton(ventanaPrincipal)
        self.stream_button.setGeometry(QtCore.QRect(470, 10, 101, 16))
        self.stream_button.setObjectName("stream_button")
        self.play_button = QtWidgets.QPushButton(ventanaPrincipal)
        self.play_button.setGeometry(QtCore.QRect(20, 160, 131, 51))
        self.play_button.setObjectName("play_button")
        self.saveAsImages_progressBar = QtWidgets.QProgressBar(ventanaPrincipal)
        self.saveAsImages_progressBar.setGeometry(QtCore.QRect(170, 90, 341, 51))
        self.saveAsImages_progressBar.setProperty("value", 0)
        self.saveAsImages_progressBar.setObjectName("saveAsImages_progressBar")
        self.filePath_edit = QtWidgets.QLineEdit(ventanaPrincipal)
        self.filePath_edit.setGeometry(QtCore.QRect(20, 50, 401, 20))
        self.filePath_edit.setObjectName("filePath_edit")
        self.selectFile_button = QtWidgets.QPushButton(ventanaPrincipal)
        self.selectFile_button.setGeometry(QtCore.QRect(430, 50, 80, 21))
        self.selectFile_button.setObjectName("selectFile_button")
        self.videoFolder_label = QtWidgets.QLabel(ventanaPrincipal)
        self.videoFolder_label.setGeometry(QtCore.QRect(20, 30, 101, 16))
        self.videoFolder_label.setObjectName("videoFolder_label")
        self.graphicsView = QtWidgets.QGraphicsView(ventanaPrincipal)
        self.graphicsView.setGeometry(QtCore.QRect(170, 150, 341, 231))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayoutWidget = QtWidgets.QWidget(ventanaPrincipal)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 300, 131, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.refreshData_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.refreshData_button.setObjectName("refreshData_button")
        self.verticalLayout.addWidget(self.refreshData_button)
        self.recDate_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.recDate_label.setObjectName("recDate_label")
        self.verticalLayout.addWidget(self.recDate_label)
        self.frameCount_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.frameCount_label.setObjectName("frameCount_label")
        self.verticalLayout.addWidget(self.frameCount_label)
        self.recSpeed_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.recSpeed_label.setObjectName("recSpeed_label")
        self.verticalLayout.addWidget(self.recSpeed_label)
        self.realTime_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.realTime_label.setObjectName("realTime_label")
        self.verticalLayout.addWidget(self.realTime_label)
        self.width_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.width_label.setObjectName("width_label")
        self.verticalLayout.addWidget(self.width_label)
        self.height_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.height_label.setObjectName("height_label")
        self.verticalLayout.addWidget(self.height_label)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(ventanaPrincipal)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(260, 390, 251, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectFps_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.selectFps_label.setObjectName("selectFps_label")
        self.horizontalLayout.addWidget(self.selectFps_label)
        self.playFps_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.playFps_label.setObjectName("playFps_label")
        self.horizontalLayout.addWidget(self.playFps_label)
        self.playLength_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.playLength_label.setObjectName("playLength_label")
        self.horizontalLayout.addWidget(self.playLength_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.playFps_slider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.playFps_slider.setMinimum(5)
        self.playFps_slider.setMaximum(300)
        self.playFps_slider.setProperty("value", 30)
        self.playFps_slider.setOrientation(QtCore.Qt.Horizontal)
        self.playFps_slider.setObjectName("playFps_slider")
        self.verticalLayout_2.addWidget(self.playFps_slider)

        self.retranslateUi(ventanaPrincipal)
        self.filePath_edit.textChanged['QString'].connect(self.refreshData_button.click)
        self.playFps_slider.valueChanged['int'].connect(self.playFps_label.setNum)
        QtCore.QMetaObject.connectSlotsByName(ventanaPrincipal)

    def retranslateUi(self, ventanaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        ventanaPrincipal.setWindowTitle(_translate("ventanaPrincipal", "Dialog"))
        self.saveAsImages_button.setText(_translate("ventanaPrincipal", "Save Video as Images"))
        self.close_button.setText(_translate("ventanaPrincipal", "Close"))
        self.status_label.setText(_translate("ventanaPrincipal", "Status"))
        self.stream_button.setText(_translate("ventanaPrincipal", "Play video while saving"))
        self.play_button.setText(_translate("ventanaPrincipal", "Play Video"))
        self.selectFile_button.setText(_translate("ventanaPrincipal", "Seleccionar"))
        self.videoFolder_label.setText(_translate("ventanaPrincipal", "Ruta al archivo de video:"))
        self.refreshData_button.setText(_translate("ventanaPrincipal", "Refresh Video Info"))
        self.recDate_label.setText(_translate("ventanaPrincipal", "Recording Date:"))
        self.frameCount_label.setText(_translate("ventanaPrincipal", "Frame Count: "))
        self.recSpeed_label.setText(_translate("ventanaPrincipal", "Recording Speed: "))
        self.realTime_label.setText(_translate("ventanaPrincipal", "Recorded Time:"))
        self.width_label.setText(_translate("ventanaPrincipal", "Width:"))
        self.height_label.setText(_translate("ventanaPrincipal", "Height:"))
        self.selectFps_label.setText(_translate("ventanaPrincipal", "Select Play framerate:"))
        self.playFps_label.setText(_translate("ventanaPrincipal", "30"))
        self.playLength_label.setText(_translate("ventanaPrincipal", "Video Length: "))

